import sys
import os
#Codigo para que VSCode acepte la ruta para Ejecutar
myDir = os.getcwd()
sys.path.append(myDir)

#Establece ruta relativa, para acceder a los paquetes
sys.path.append("..")

from PyQt5 import QtCore, QtGui, QtWidgets


class Empleados(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(657, 552)
        self.pantalla_tab = QtWidgets.QTabWidget(Form)
        self.pantalla_tab.setEnabled(True)
        self.pantalla_tab.setGeometry(QtCore.QRect(10, 10, 641, 531))
        self.pantalla_tab.setObjectName("pantalla_tab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_usuarios = QtWidgets.QGroupBox(self.tab)
        self.groupBox_usuarios.setEnabled(True)
        self.groupBox_usuarios.setGeometry(QtCore.QRect(10, 10, 611, 211))
        self.groupBox_usuarios.setTitle("")
        self.groupBox_usuarios.setObjectName("groupBox_usuarios")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_usuarios)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 221, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.chbx_activo = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.chbx_activo.setObjectName("chbx_activo")
        self.gridLayout.addWidget(self.chbx_activo, 0, 2, 1, 1)
        self.txt_dni = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_dni.setObjectName("txt_dni")
        self.gridLayout.addWidget(self.txt_dni, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.date_nacimiento_usuario = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.date_nacimiento_usuario.setObjectName("date_nacimiento_usuario")
        self.gridLayout.addWidget(self.date_nacimiento_usuario, 4, 1, 1, 2)
        self.txt_nombres = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_nombres.setObjectName("txt_nombres")
        self.gridLayout.addWidget(self.txt_nombres, 1, 1, 1, 2)
        self.txt_apellidos = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_apellidos.setObjectName("txt_apellidos")
        self.gridLayout.addWidget(self.txt_apellidos, 2, 1, 1, 2)
        self.cbx_sexo_usuario = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbx_sexo_usuario.setObjectName("cbx_sexo_usuario")
        self.cbx_sexo_usuario.addItem("")
        self.cbx_sexo_usuario.addItem("")
        self.gridLayout.addWidget(self.cbx_sexo_usuario, 3, 1, 1, 2)
        self.chbx_activo.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_9.raise_()
        self.date_nacimiento_usuario.raise_()
        self.txt_nombres.raise_()
        self.txt_apellidos.raise_()
        self.cbx_sexo_usuario.raise_()
        self.txt_dni.raise_()
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_usuarios)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(240, 10, 191, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 2, 1, 1)
        self.txt_usuario = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txt_usuario.setObjectName("txt_usuario")
        self.gridLayout_2.addWidget(self.txt_usuario, 3, 3, 1, 1)
        self.txt_password = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txt_password.setObjectName("txt_password")
        self.gridLayout_2.addWidget(self.txt_password, 4, 3, 1, 1)
        self.txt_telefono = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txt_telefono.setObjectName("txt_telefono")
        self.gridLayout_2.addWidget(self.txt_telefono, 0, 3, 1, 1)
        self.txt_email = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txt_email.setObjectName("txt_email")
        self.gridLayout_2.addWidget(self.txt_email, 2, 3, 1, 1)
        self.cbx_rol_usuario = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.cbx_rol_usuario.setObjectName("cbx_rol_usuario")
        self.cbx_rol_usuario.addItem("")
        self.cbx_rol_usuario.addItem("")
        self.cbx_rol_usuario.addItem("")
        self.gridLayout_2.addWidget(self.cbx_rol_usuario, 5, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_usuarios)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 170, 239, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_crear_usuario = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_crear_usuario.setObjectName("btn_crear_usuario")
        self.horizontalLayout.addWidget(self.btn_crear_usuario)
        self.btn_modificar_usuario = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_modificar_usuario.setObjectName("btn_modificar_usuario")
        self.horizontalLayout.addWidget(self.btn_modificar_usuario)
        self.btn_eliminar_usuario = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_eliminar_usuario.setObjectName("btn_eliminar_usuario")
        self.horizontalLayout.addWidget(self.btn_eliminar_usuario)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_usuarios)
        self.groupBox_2.setGeometry(QtCore.QRect(440, 10, 161, 161))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.lbl_icono_usuario = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_icono_usuario.setGeometry(QtCore.QRect(10, 10, 141, 141))
        self.lbl_icono_usuario.setText("")
        self.lbl_icono_usuario.setPixmap(QtGui.QPixmap("../resource/image/hombre.png"))
        self.lbl_icono_usuario.setScaledContents(True)
        self.lbl_icono_usuario.setObjectName("lbl_icono_usuario")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_usuarios)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(440, 180, 158, 25))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.cbx_buscar_usuario = QtWidgets.QComboBox(self.tab)
        self.cbx_buscar_usuario.setGeometry(QtCore.QRect(210, 230, 131, 22))
        self.cbx_buscar_usuario.setObjectName("cbx_buscar_usuario")
        self.cbx_buscar_usuario.addItem("")
        self.cbx_buscar_usuario.addItem("")
        self.txt_buscar_usuario = QtWidgets.QLineEdit(self.tab)
        self.txt_buscar_usuario.setGeometry(QtCore.QRect(350, 230, 157, 20))
        self.txt_buscar_usuario.setObjectName("txt_buscar_usuario")
        self.tabla_usuarios = QtWidgets.QTableWidget(self.tab)
        self.tabla_usuarios.setGeometry(QtCore.QRect(10, 260, 611, 231))
        self.tabla_usuarios.setObjectName("tabla_usuarios")
        self.tabla_usuarios.setColumnCount(10)
        self.tabla_usuarios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_usuarios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_usuarios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_usuarios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_usuarios.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_usuarios.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_usuarios.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_usuarios.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_usuarios.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_usuarios.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_usuarios.setHorizontalHeaderItem(9, item)
        self.btn_buscar_usuario = QtWidgets.QPushButton(self.tab)
        self.btn_buscar_usuario.setGeometry(QtCore.QRect(520, 230, 75, 23))
        self.btn_buscar_usuario.setObjectName("btn_buscar_usuario")
        self.pantalla_tab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabla_roles = QtWidgets.QTableWidget(self.tab_2)
        self.tabla_roles.setGeometry(QtCore.QRect(10, 270, 611, 221))
        self.tabla_roles.setObjectName("tabla_roles")
        self.tabla_roles.setColumnCount(3)
        self.tabla_roles.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_roles.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_roles.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_roles.setHorizontalHeaderItem(2, item)
        self.txt_buscar_rol = QtWidgets.QLineEdit(self.tab_2)
        self.txt_buscar_rol.setGeometry(QtCore.QRect(370, 240, 157, 20))
        self.txt_buscar_rol.setObjectName("txt_buscar_rol")
        self.cbx_buscar_rol = QtWidgets.QComboBox(self.tab_2)
        self.cbx_buscar_rol.setGeometry(QtCore.QRect(230, 240, 131, 22))
        self.cbx_buscar_rol.setObjectName("cbx_buscar_rol")
        self.cbx_buscar_rol.addItem("")
        self.btn_buscar_rol = QtWidgets.QPushButton(self.tab_2)
        self.btn_buscar_rol.setGeometry(QtCore.QRect(540, 240, 75, 23))
        self.btn_buscar_rol.setObjectName("btn_buscar_rol")
        self.groupBox_roles = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_roles.setEnabled(True)
        self.groupBox_roles.setGeometry(QtCore.QRect(10, 10, 601, 221))
        self.groupBox_roles.setTitle("")
        self.groupBox_roles.setObjectName("groupBox_roles")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_roles)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 180, 239, 25))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_crear_rol = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_crear_rol.setObjectName("btn_crear_rol")
        self.horizontalLayout_3.addWidget(self.btn_crear_rol)
        self.btn_modificar_rol = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_modificar_rol.setObjectName("btn_modificar_rol")
        self.horizontalLayout_3.addWidget(self.btn_modificar_rol)
        self.btn_eliminar_rol = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_eliminar_rol.setObjectName("btn_eliminar_rol")
        self.horizontalLayout_3.addWidget(self.btn_eliminar_rol)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_roles)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 271, 161))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.txt_nombre_rol = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.txt_nombre_rol.setObjectName("txt_nombre_rol")
        self.gridLayout_4.addWidget(self.txt_nombre_rol, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.txt_descripcion_rol = QtWidgets.QTextEdit(self.gridLayoutWidget_4)
        self.txt_descripcion_rol.setObjectName("txt_descripcion_rol")
        self.gridLayout_4.addWidget(self.txt_descripcion_rol, 2, 1, 1, 1)
        self.txt_id_rol = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.txt_id_rol.setObjectName("txt_id_rol")
        self.gridLayout_4.addWidget(self.txt_id_rol, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_roles)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(310, 10, 261, 191))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cbx_permisos_productos = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.cbx_permisos_productos.setObjectName("cbx_permisos_productos")
        self.cbx_permisos_productos.addItem("")
        self.cbx_permisos_productos.addItem("")
        self.gridLayout_3.addWidget(self.cbx_permisos_productos, 4, 1, 1, 1)
        self.cbx_permisos_almacen = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.cbx_permisos_almacen.setObjectName("cbx_permisos_almacen")
        self.cbx_permisos_almacen.addItem("")
        self.cbx_permisos_almacen.addItem("")
        self.gridLayout_3.addWidget(self.cbx_permisos_almacen, 5, 1, 1, 1)
        self.cbx_permisos_clientes = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.cbx_permisos_clientes.setObjectName("cbx_permisos_clientes")
        self.cbx_permisos_clientes.addItem("")
        self.cbx_permisos_clientes.addItem("")
        self.gridLayout_3.addWidget(self.cbx_permisos_clientes, 0, 1, 1, 1)
        self.cbx_permisos_proveedores_2 = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.cbx_permisos_proveedores_2.setObjectName("cbx_permisos_proveedores_2")
        self.cbx_permisos_proveedores_2.addItem("")
        self.cbx_permisos_proveedores_2.addItem("")
        self.gridLayout_3.addWidget(self.cbx_permisos_proveedores_2, 3, 1, 1, 1)
        self.cbx_permisos_empleados = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.cbx_permisos_empleados.setObjectName("cbx_permisos_empleados")
        self.cbx_permisos_empleados.addItem("")
        self.cbx_permisos_empleados.addItem("")
        self.gridLayout_3.addWidget(self.cbx_permisos_empleados, 2, 1, 1, 1)
        self.chk_ventas = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.chk_ventas.setObjectName("chk_ventas")
        self.gridLayout_3.addWidget(self.chk_ventas, 6, 0, 1, 1)
        self.chk_empleados = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.chk_empleados.setObjectName("chk_empleados")
        self.gridLayout_3.addWidget(self.chk_empleados, 2, 0, 1, 1)
        self.chk_clientes = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.chk_clientes.setObjectName("chk_clientes")
        self.gridLayout_3.addWidget(self.chk_clientes, 0, 0, 1, 1)
        self.chk_proveedores = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.chk_proveedores.setObjectName("chk_proveedores")
        self.gridLayout_3.addWidget(self.chk_proveedores, 3, 0, 1, 1)
        self.chk_productos = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.chk_productos.setObjectName("chk_productos")
        self.gridLayout_3.addWidget(self.chk_productos, 4, 0, 1, 1)
        self.chk_almacen = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.chk_almacen.setObjectName("chk_almacen")
        self.gridLayout_3.addWidget(self.chk_almacen, 5, 0, 1, 1)
        self.chk_mantenimiento = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.chk_mantenimiento.setObjectName("chk_mantenimiento")
        self.gridLayout_3.addWidget(self.chk_mantenimiento, 7, 0, 1, 1)
        self.cbx_permisos_ventas = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.cbx_permisos_ventas.setObjectName("cbx_permisos_ventas")
        self.cbx_permisos_ventas.addItem("")
        self.cbx_permisos_ventas.addItem("")
        self.gridLayout_3.addWidget(self.cbx_permisos_ventas, 6, 1, 1, 1)
        self.pantalla_tab.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.pantalla_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Gestion Usuarios"))
        self.chbx_activo.setText(_translate("Form", "Activo"))
        self.label_4.setText(_translate("Form", "F. Nacimiento:"))
        self.label_2.setText(_translate("Form", "Apellidos:"))
        self.label.setText(_translate("Form", "Nombres:"))
        self.label_3.setText(_translate("Form", "Sexo:"))
        self.label_9.setText(_translate("Form", "DNI:"))
        self.cbx_sexo_usuario.setItemText(0, _translate("Form", "F"))
        self.cbx_sexo_usuario.setItemText(1, _translate("Form", "M"))
        self.label_10.setText(_translate("Form", "Rol:"))
        self.label_6.setText(_translate("Form", "Email:"))
        self.label_7.setText(_translate("Form", "Usuario:"))
        self.label_8.setText(_translate("Form", "Contraseña:"))
        self.cbx_rol_usuario.setItemText(0, _translate("Form", "Administrador"))
        self.cbx_rol_usuario.setItemText(1, _translate("Form", "Caja"))
        self.cbx_rol_usuario.setItemText(2, _translate("Form", "Vendedor"))
        self.label_5.setText(_translate("Form", "Teléfono:"))
        self.btn_crear_usuario.setText(_translate("Form", "Crear"))
        self.btn_modificar_usuario.setText(_translate("Form", "Modificar"))
        self.btn_eliminar_usuario.setText(_translate("Form", "Eliminar"))
        self.pushButton.setText(_translate("Form", "Insertar"))
        self.pushButton_5.setText(_translate("Form", "Ver"))
        self.cbx_buscar_usuario.setItemText(0, _translate("Form", "Nombre"))
        self.cbx_buscar_usuario.setItemText(1, _translate("Form", "ID"))
        item = self.tabla_usuarios.horizontalHeaderItem(0)
        item.setText(_translate("Form", "DNI"))
        item = self.tabla_usuarios.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Permisos"))
        item = self.tabla_usuarios.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Nombres"))
        item = self.tabla_usuarios.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Apellidos"))
        item = self.tabla_usuarios.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Sexo"))
        item = self.tabla_usuarios.horizontalHeaderItem(5)
        item.setText(_translate("Form", "F. Nacimiento"))
        item = self.tabla_usuarios.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Telefono"))
        item = self.tabla_usuarios.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Email"))
        item = self.tabla_usuarios.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Cargo"))
        item = self.tabla_usuarios.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Usuario"))
        self.btn_buscar_usuario.setText(_translate("Form", "Buscar"))
        self.pantalla_tab.setTabText(self.pantalla_tab.indexOf(self.tab), _translate("Form", "Usuario"))
        item = self.tabla_roles.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Rol"))
        item = self.tabla_roles.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Area"))
        item = self.tabla_roles.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Permisos"))
        self.cbx_buscar_rol.setItemText(0, _translate("Form", "Rol"))
        self.btn_buscar_rol.setText(_translate("Form", "Buscar"))
        self.btn_crear_rol.setText(_translate("Form", "Crear"))
        self.btn_modificar_rol.setText(_translate("Form", "Modificar"))
        self.btn_eliminar_rol.setText(_translate("Form", "Eliminar"))
        self.label_13.setText(_translate("Form", "Descripcion:"))
        self.label_12.setText(_translate("Form", "Rol:"))
        self.label_11.setText(_translate("Form", "ID"))
        self.cbx_permisos_productos.setItemText(0, _translate("Form", "Leer"))
        self.cbx_permisos_productos.setItemText(1, _translate("Form", "Leer y escribir"))
        self.cbx_permisos_almacen.setItemText(0, _translate("Form", "Leer"))
        self.cbx_permisos_almacen.setItemText(1, _translate("Form", "Leer y escribir"))
        self.cbx_permisos_clientes.setItemText(0, _translate("Form", "Leer"))
        self.cbx_permisos_clientes.setItemText(1, _translate("Form", "Leer y escribir"))
        self.cbx_permisos_proveedores_2.setItemText(0, _translate("Form", "Leer"))
        self.cbx_permisos_proveedores_2.setItemText(1, _translate("Form", "Leer y escribir"))
        self.cbx_permisos_empleados.setItemText(0, _translate("Form", "Leer"))
        self.cbx_permisos_empleados.setItemText(1, _translate("Form", "Leer y escribir"))
        self.chk_ventas.setText(_translate("Form", "Ventas"))
        self.chk_empleados.setText(_translate("Form", "Empleados"))
        self.chk_clientes.setText(_translate("Form", "Clientes"))
        self.chk_proveedores.setText(_translate("Form", "Proveedores"))
        self.chk_productos.setText(_translate("Form", "Productos"))
        self.chk_almacen.setText(_translate("Form", "Almacen"))
        self.chk_mantenimiento.setText(_translate("Form", "Mantenimiento"))
        self.cbx_permisos_ventas.setItemText(0, _translate("Form", "Leer"))
        self.cbx_permisos_ventas.setItemText(1, _translate("Form", "Leer y escribir"))
        self.pantalla_tab.setTabText(self.pantalla_tab.indexOf(self.tab_2), _translate("Form", "Roles y permisos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Empleados()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
