import sys
import os


#Establece ruta relativa, para acceder a los paquetes
sys.path.append("..")
#Codigo para que VSCode acepte la ruta para Ejecutar
myDir = os.getcwd()
sys.path.append(myDir)
from PyQt5 import QtCore, QtGui, QtWidgets


class Productos_frm(object):
    def setupUi(self, frm_productos):
        frm_productos.setObjectName("frm_productos")
        frm_productos.resize(597, 564)
        self.tabla_productos = QtWidgets.QTableWidget(frm_productos)
        self.tabla_productos.setGeometry(QtCore.QRect(10, 280, 581, 271))
        self.tabla_productos.setObjectName("tabla_productos")
        self.tabla_productos.setColumnCount(6)
        self.tabla_productos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(5, item)
        self.txt_buscar = QtWidgets.QLineEdit(frm_productos)
        self.txt_buscar.setGeometry(QtCore.QRect(320, 250, 181, 20))
        self.txt_buscar.setObjectName("txt_buscar")
        self.btn_buscar = QtWidgets.QPushButton(frm_productos)
        self.btn_buscar.setGeometry(QtCore.QRect(510, 250, 75, 23))
        self.btn_buscar.setObjectName("btn_buscar")
        self.cbx_buscar = QtWidgets.QComboBox(frm_productos)
        self.cbx_buscar.setGeometry(QtCore.QRect(150, 250, 151, 22))
        self.cbx_buscar.setObjectName("cbx_buscar")
        self.cbx_buscar.addItem("")
        self.cbx_buscar.addItem("")
        self.cbx_buscar.addItem("")
        self.cbx_buscar.addItem("")
        self.cbx_buscar.addItem("")
        self.gpBox_formulario = QtWidgets.QGroupBox(frm_productos)
        self.gpBox_formulario.setGeometry(QtCore.QRect(10, 10, 301, 231))
        self.gpBox_formulario.setTitle("")
        self.gpBox_formulario.setObjectName("gpBox_formulario")
        self.gridLayoutWidget = QtWidgets.QWidget(self.gpBox_formulario)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 282, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txt_codigo = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_codigo.setObjectName("txt_codigo")
        self.gridLayout.addWidget(self.txt_codigo, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 2, 1, 1)
        self.txt_nombre = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_nombre.setObjectName("txt_nombre")
        self.gridLayout.addWidget(self.txt_nombre, 1, 1, 1, 2)
        self.cbx_categoria = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbx_categoria.setObjectName("cbx_categoria")
        self.cbx_categoria.addItem("")
        self.cbx_categoria.addItem("")
        self.gridLayout.addWidget(self.cbx_categoria, 2, 1, 1, 2)
        self.txt_precio_compra = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_precio_compra.setObjectName("txt_precio_compra")
        self.gridLayout.addWidget(self.txt_precio_compra, 3, 1, 1, 2)
        self.cbx_proveedor = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbx_proveedor.setObjectName("cbx_proveedor")
        self.cbx_proveedor.addItem("")
        self.cbx_proveedor.addItem("")
        self.gridLayout.addWidget(self.cbx_proveedor, 4, 1, 1, 2)
        self.txt_precio_venta = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_precio_venta.setObjectName("txt_precio_venta")
        self.gridLayout.addWidget(self.txt_precio_venta, 5, 1, 1, 2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.gpBox_formulario)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 200, 261, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_agregar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_agregar.setObjectName("btn_agregar")
        self.horizontalLayout.addWidget(self.btn_agregar)
        self.btn_modificar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_modificar.setObjectName("btn_modificar")
        self.horizontalLayout.addWidget(self.btn_modificar)
        self.btn_eliminar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.horizontalLayout.addWidget(self.btn_eliminar)
        self.gpBox_foto = QtWidgets.QGroupBox(frm_productos)
        self.gpBox_foto.setGeometry(QtCore.QRect(320, 10, 181, 181))
        self.gpBox_foto.setObjectName("gpBox_foto")
        self.lbl_foto = QtWidgets.QLabel(self.gpBox_foto)
        self.lbl_foto.setGeometry(QtCore.QRect(10, 20, 161, 151))
        self.lbl_foto.setText("")
        self.lbl_foto.setPixmap(QtGui.QPixmap("../../Layout/imagenes/taladro.png"))
        self.lbl_foto.setScaledContents(True)
        self.lbl_foto.setObjectName("lbl_foto")
        self.verticalLayoutWidget = QtWidgets.QWidget(frm_productos)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(510, 20, 81, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_insertar_foto = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_insertar_foto.setObjectName("btn_insertar_foto")
        self.verticalLayout.addWidget(self.btn_insertar_foto)
        self.btn_mostrar_foto = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_mostrar_foto.setObjectName("btn_mostrar_foto")
        self.verticalLayout.addWidget(self.btn_mostrar_foto)

        self.retranslateUi(frm_productos)
        QtCore.QMetaObject.connectSlotsByName(frm_productos)

    def retranslateUi(self, frm_productos):
        _translate = QtCore.QCoreApplication.translate
        frm_productos.setWindowTitle(_translate("frm_productos", "Form"))
        item = self.tabla_productos.horizontalHeaderItem(0)
        item.setText(_translate("frm_productos", "New Column"))
        item = self.tabla_productos.horizontalHeaderItem(1)
        item.setText(_translate("frm_productos", "Codigo"))
        item = self.tabla_productos.horizontalHeaderItem(2)
        item.setText(_translate("frm_productos", "Categoria"))
        item = self.tabla_productos.horizontalHeaderItem(3)
        item.setText(_translate("frm_productos", "New Column"))
        item = self.tabla_productos.horizontalHeaderItem(4)
        item.setText(_translate("frm_productos", "New Column"))
        item = self.tabla_productos.horizontalHeaderItem(5)
        item.setText(_translate("frm_productos", "Proveedor"))
        self.btn_buscar.setText(_translate("frm_productos", "Buscar"))
        self.cbx_buscar.setItemText(0, _translate("frm_productos", "Codigo"))
        self.cbx_buscar.setItemText(1, _translate("frm_productos", "Nombre"))
        self.cbx_buscar.setItemText(2, _translate("frm_productos", "Categoria"))
        self.cbx_buscar.setItemText(3, _translate("frm_productos", "Precio compra"))
        self.cbx_buscar.setItemText(4, _translate("frm_productos", "Precio venta"))
        self.label_3.setText(_translate("frm_productos", "Categoria:"))
        self.label_4.setText(_translate("frm_productos", "Precio venta:"))
        self.label_2.setText(_translate("frm_productos", "Nombre:"))
        self.label.setText(_translate("frm_productos", "Codigo:"))
        self.label_5.setText(_translate("frm_productos", "Precio compra:"))
        self.label_6.setText(_translate("frm_productos", "Proveedor:"))
        self.checkBox.setText(_translate("frm_productos", "Desbloquear"))
        self.cbx_categoria.setItemText(0, _translate("frm_productos", "Herramienta"))
        self.cbx_categoria.setItemText(1, _translate("frm_productos", "Material construccion"))
        self.cbx_proveedor.setItemText(0, _translate("frm_productos", "Aceros Arequipa"))
        self.cbx_proveedor.setItemText(1, _translate("frm_productos", "Tuberias PAVCO"))
        self.btn_agregar.setText(_translate("frm_productos", "Agregar"))
        self.btn_modificar.setText(_translate("frm_productos", "Modificar"))
        self.btn_eliminar.setText(_translate("frm_productos", "Eliminar"))
        self.gpBox_foto.setTitle(_translate("frm_productos", "Foto"))
        self.btn_insertar_foto.setText(_translate("frm_productos", "Insertar"))
        self.btn_mostrar_foto.setText(_translate("frm_productos", "Mostrar foto"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frm_productos = QtWidgets.QWidget()
    ui = Productos_frm()
    ui.setupUi(frm_productos)
    frm_productos.show()
    sys.exit(app.exec_())
