import sys
import os


#Establece ruta relativa, para acceder a los paquetes
sys.path.append("..")
#Codigo para que VSCode acepte la ruta para Ejecutar
myDir = os.getcwd()
sys.path.append(myDir)
from PyQt5 import QtCore, QtGui, QtWidgets


class Principal_frm(object):
    def setupUi(self, frm_principal):
        frm_principal.setObjectName("frm_principal")
        frm_principal.resize(755, 501)
        self.centralwidget = QtWidgets.QWidget(frm_principal)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 891, 121))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 668, 82))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_mantenimiento = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mantenimiento.sizePolicy().hasHeightForWidth())
        self.btn_mantenimiento.setSizePolicy(sizePolicy)
        self.btn_mantenimiento.setMinimumSize(QtCore.QSize(90, 80))
        self.btn_mantenimiento.setMaximumSize(QtCore.QSize(90, 80))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/image/caja-de-herramientas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_mantenimiento.setIcon(icon)
        self.btn_mantenimiento.setIconSize(QtCore.QSize(50, 50))
        self.btn_mantenimiento.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_mantenimiento.setObjectName("btn_mantenimiento")
        self.gridLayout.addWidget(self.btn_mantenimiento, 0, 6, 1, 1)
        self.btn_proveedores = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_proveedores.sizePolicy().hasHeightForWidth())
        self.btn_proveedores.setSizePolicy(sizePolicy)
        self.btn_proveedores.setMinimumSize(QtCore.QSize(90, 80))
        self.btn_proveedores.setMaximumSize(QtCore.QSize(90, 80))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resource/image/camion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_proveedores.setIcon(icon1)
        self.btn_proveedores.setIconSize(QtCore.QSize(50, 50))
        self.btn_proveedores.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_proveedores.setObjectName("btn_proveedores")
        self.gridLayout.addWidget(self.btn_proveedores, 0, 3, 1, 1)
        self.btn_almacen = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_almacen.sizePolicy().hasHeightForWidth())
        self.btn_almacen.setSizePolicy(sizePolicy)
        self.btn_almacen.setMinimumSize(QtCore.QSize(90, 80))
        self.btn_almacen.setMaximumSize(QtCore.QSize(90, 80))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resource/image/almacen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_almacen.setIcon(icon2)
        self.btn_almacen.setIconSize(QtCore.QSize(50, 50))
        self.btn_almacen.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_almacen.setObjectName("btn_almacen")
        self.gridLayout.addWidget(self.btn_almacen, 0, 1, 1, 1)
        self.btn_caja = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_caja.sizePolicy().hasHeightForWidth())
        self.btn_caja.setSizePolicy(sizePolicy)
        self.btn_caja.setMinimumSize(QtCore.QSize(90, 80))
        self.btn_caja.setMaximumSize(QtCore.QSize(90, 80))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resource/image/caja_venta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_caja.setIcon(icon3)
        self.btn_caja.setIconSize(QtCore.QSize(50, 50))
        self.btn_caja.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_caja.setObjectName("btn_caja")
        self.gridLayout.addWidget(self.btn_caja, 0, 0, 1, 1)
        self.btn_empleados = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_empleados.sizePolicy().hasHeightForWidth())
        self.btn_empleados.setSizePolicy(sizePolicy)
        self.btn_empleados.setMinimumSize(QtCore.QSize(90, 80))
        self.btn_empleados.setMaximumSize(QtCore.QSize(90, 80))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resource/image/gerente.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_empleados.setIcon(icon4)
        self.btn_empleados.setIconSize(QtCore.QSize(50, 50))
        self.btn_empleados.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_empleados.setObjectName("btn_empleados")
        self.gridLayout.addWidget(self.btn_empleados, 0, 5, 1, 1)
        self.btn_productos = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_productos.sizePolicy().hasHeightForWidth())
        self.btn_productos.setSizePolicy(sizePolicy)
        self.btn_productos.setMinimumSize(QtCore.QSize(90, 80))
        self.btn_productos.setMaximumSize(QtCore.QSize(90, 80))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resource/image/caja.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_productos.setIcon(icon5)
        self.btn_productos.setIconSize(QtCore.QSize(50, 50))
        self.btn_productos.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_productos.setObjectName("btn_productos")
        self.gridLayout.addWidget(self.btn_productos, 0, 2, 1, 1)
        self.btn_clientes = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clientes.sizePolicy().hasHeightForWidth())
        self.btn_clientes.setSizePolicy(sizePolicy)
        self.btn_clientes.setMinimumSize(QtCore.QSize(90, 80))
        self.btn_clientes.setMaximumSize(QtCore.QSize(90, 80))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resource/image/equipo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_clientes.setIcon(icon6)
        self.btn_clientes.setIconSize(QtCore.QSize(50, 50))
        self.btn_clientes.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_clientes.setObjectName("btn_clientes")
        self.gridLayout.addWidget(self.btn_clientes, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 250, 211, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Imagenes/logo_ferremax.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        frm_principal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(frm_principal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 755, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Sesion = QtWidgets.QMenu(self.menubar)
        self.menu_Sesion.setObjectName("menu_Sesion")
        self.menu_Clientes = QtWidgets.QMenu(self.menubar)
        self.menu_Clientes.setObjectName("menu_Clientes")
        self.menu_Producto = QtWidgets.QMenu(self.menubar)
        self.menu_Producto.setObjectName("menu_Producto")
        self.menu_Caja = QtWidgets.QMenu(self.menubar)
        self.menu_Caja.setObjectName("menu_Caja")
        self.menu_Ventas = QtWidgets.QMenu(self.menubar)
        self.menu_Ventas.setObjectName("menu_Ventas")
        self.menu_Mantenimiento = QtWidgets.QMenu(self.menubar)
        self.menu_Mantenimiento.setObjectName("menu_Mantenimiento")
        self.submenu_bd = QtWidgets.QMenu(self.menu_Mantenimiento)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resource/image/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submenu_bd.setIcon(icon7)
        self.submenu_bd.setObjectName("submenu_bd")
        frm_principal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(frm_principal)
        self.statusbar.setObjectName("statusbar")
        frm_principal.setStatusBar(self.statusbar)
        self.action_Open = QtWidgets.QAction(frm_principal)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Imagenes/iniciar-sesion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon8)
        self.action_Open.setObjectName("action_Open")
        self.action_Cerrar_Sesion = QtWidgets.QAction(frm_principal)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Imagenes/cerrar-sesion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Cerrar_Sesion.setIcon(icon9)
        self.action_Cerrar_Sesion.setObjectName("action_Cerrar_Sesion")
        self.action_Info = QtWidgets.QAction(frm_principal)
        self.action_Info.setObjectName("action_Info")
        self.action_Importar_BD = QtWidgets.QAction(frm_principal)
        self.action_Importar_BD.setObjectName("action_Importar_BD")
        self.submenu_personalizar = QtWidgets.QAction(frm_principal)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("resource/image/paleta-de-color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submenu_personalizar.setIcon(icon10)
        self.submenu_personalizar.setObjectName("submenu_personalizar")
        self.actionCrear_respaldo = QtWidgets.QAction(frm_principal)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("resource/image/descargar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrear_respaldo.setIcon(icon11)
        self.actionCrear_respaldo.setObjectName("actionCrear_respaldo")
        self.actionImportar_BD = QtWidgets.QAction(frm_principal)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("resource/image/subir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImportar_BD.setIcon(icon12)
        self.actionImportar_BD.setObjectName("actionImportar_BD")
        self.actionReportar_incidencias = QtWidgets.QAction(frm_principal)
        self.actionReportar_incidencias.setObjectName("actionReportar_incidencias")
        self.actionCerrar_sesion = QtWidgets.QAction(frm_principal)
        self.actionCerrar_sesion.setObjectName("actionCerrar_sesion")
        self.actionSalir_y_cerrar_sesion = QtWidgets.QAction(frm_principal)
        self.actionSalir_y_cerrar_sesion.setObjectName("actionSalir_y_cerrar_sesion")
        self.actionCrear_back_up = QtWidgets.QAction(frm_principal)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("resource/image/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrear_back_up.setIcon(icon13)
        self.actionCrear_back_up.setObjectName("actionCrear_back_up")
        self.menu_Sesion.addAction(self.action_Cerrar_Sesion)
        self.menu_Sesion.addAction(self.action_Info)
        self.menu_Sesion.addAction(self.actionReportar_incidencias)
        self.menu_Sesion.addAction(self.actionCerrar_sesion)
        self.menu_Sesion.addAction(self.actionSalir_y_cerrar_sesion)
        self.submenu_bd.addAction(self.actionCrear_respaldo)
        self.submenu_bd.addAction(self.actionImportar_BD)
        self.submenu_bd.addAction(self.actionCrear_back_up)
        self.menu_Mantenimiento.addAction(self.submenu_bd.menuAction())
        self.menu_Mantenimiento.addAction(self.submenu_personalizar)
        self.menubar.addAction(self.menu_Sesion.menuAction())
        self.menubar.addAction(self.menu_Clientes.menuAction())
        self.menubar.addAction(self.menu_Producto.menuAction())
        self.menubar.addAction(self.menu_Caja.menuAction())
        self.menubar.addAction(self.menu_Ventas.menuAction())
        self.menubar.addAction(self.menu_Mantenimiento.menuAction())

        self.retranslateUi(frm_principal)
        QtCore.QMetaObject.connectSlotsByName(frm_principal)

    def retranslateUi(self, frm_principal):
        _translate = QtCore.QCoreApplication.translate
        frm_principal.setWindowTitle(_translate("frm_principal", "Ventana Principal"))
        self.btn_mantenimiento.setText(_translate("frm_principal", "Mantenimiento"))
        self.btn_proveedores.setText(_translate("frm_principal", "Proveedores"))
        self.btn_almacen.setText(_translate("frm_principal", "Almacen"))
        self.btn_caja.setText(_translate("frm_principal", "Caja"))
        self.btn_empleados.setText(_translate("frm_principal", "Empleados"))
        self.btn_productos.setText(_translate("frm_principal", "Productos"))
        self.btn_clientes.setText(_translate("frm_principal", "Clientes"))
        self.menu_Sesion.setTitle(_translate("frm_principal", "&Usuario"))
        self.menu_Clientes.setTitle(_translate("frm_principal", "&Clientes"))
        self.menu_Producto.setTitle(_translate("frm_principal", "&Producto"))
        self.menu_Caja.setTitle(_translate("frm_principal", "&Caja"))
        self.menu_Ventas.setTitle(_translate("frm_principal", "&Ventas"))
        self.menu_Mantenimiento.setTitle(_translate("frm_principal", "&Mantenimiento"))
        self.submenu_bd.setTitle(_translate("frm_principal", "Base de datos"))
        self.action_Open.setText(_translate("frm_principal", "&Nueva Sesion"))
        self.action_Cerrar_Sesion.setText(_translate("frm_principal", "Detalles"))
        self.action_Info.setText(_translate("frm_principal", "Marcar asistencia"))
        self.action_Importar_BD.setText(_translate("frm_principal", "Importar BD"))
        self.submenu_personalizar.setText(_translate("frm_principal", "Personalizar"))
        self.actionCrear_respaldo.setText(_translate("frm_principal", "Exportar BD"))
        self.actionImportar_BD.setText(_translate("frm_principal", "Importar BD"))
        self.actionReportar_incidencias.setText(_translate("frm_principal", "Reportar incidencias"))
        self.actionCerrar_sesion.setText(_translate("frm_principal", "Cerrar sesion"))
        self.actionSalir_y_cerrar_sesion.setText(_translate("frm_principal", "Salir"))
        self.actionCrear_back_up.setText(_translate("frm_principal", "Crear back-up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frm_principal = QtWidgets.QMainWindow()
    ui = Principal_frm()
    ui.setupUi(frm_principal)
    frm_principal.show()
    sys.exit(app.exec_())
