
from PyQt5 import QtCore, QtGui, QtWidgets


class Proveedores(object):
    def setupUi(self, Proveedores):
        Proveedores.setObjectName("Proveedores")
        Proveedores.resize(580, 471)
        self.tabla_proveedores = QtWidgets.QTableWidget(Proveedores)
        self.tabla_proveedores.setGeometry(QtCore.QRect(10, 230, 561, 231))
        self.tabla_proveedores.setObjectName("tabla_proveedores")
        self.tabla_proveedores.setColumnCount(5)
        self.tabla_proveedores.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_proveedores.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_proveedores.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_proveedores.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_proveedores.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_proveedores.setHorizontalHeaderItem(4, item)
        self.btn_buscar = QtWidgets.QPushButton(Proveedores)
        self.btn_buscar.setGeometry(QtCore.QRect(470, 200, 75, 23))
        self.btn_buscar.setObjectName("btn_buscar")
        self.txt_buscar = QtWidgets.QLineEdit(Proveedores)
        self.txt_buscar.setGeometry(QtCore.QRect(330, 200, 131, 20))
        self.txt_buscar.setObjectName("txt_buscar")
        self.cbx_buscar = QtWidgets.QComboBox(Proveedores)
        self.cbx_buscar.setGeometry(QtCore.QRect(190, 200, 131, 22))
        self.cbx_buscar.setObjectName("cbx_buscar")
        self.cbx_buscar.addItem("")
        self.cbx_buscar.addItem("")
        self.cbx_buscar.addItem("")
        self.cbx_buscar.addItem("")
        self.groupBox = QtWidgets.QGroupBox(Proveedores)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 561, 181))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 401, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.txt_ruc = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_ruc.setObjectName("txt_ruc")
        self.gridLayout.addWidget(self.txt_ruc, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.txt_telefono = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_telefono.setObjectName("txt_telefono")
        self.gridLayout.addWidget(self.txt_telefono, 1, 3, 1, 1)
        self.txt_nombre = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_nombre.setObjectName("txt_nombre")
        self.gridLayout.addWidget(self.txt_nombre, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.txt_direccion = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_direccion.setObjectName("txt_direccion")
        self.gridLayout.addWidget(self.txt_direccion, 2, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.txt_email = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txt_email.setObjectName("txt_email")
        self.gridLayout.addWidget(self.txt_email, 5, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 140, 239, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_crear = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_crear.setObjectName("btn_crear")
        self.horizontalLayout.addWidget(self.btn_crear)
        self.btn_modificar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_modificar.setObjectName("btn_modificar")
        self.horizontalLayout.addWidget(self.btn_modificar)
        self.btn_eliminar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.horizontalLayout.addWidget(self.btn_eliminar)

        self.retranslateUi(Proveedores)
        QtCore.QMetaObject.connectSlotsByName(Proveedores)

    def retranslateUi(self, Proveedores):
        _translate = QtCore.QCoreApplication.translate
        Proveedores.setWindowTitle(_translate("Proveedores", "Proveedores"))
        item = self.tabla_proveedores.horizontalHeaderItem(0)
        item.setText(_translate("Proveedores", "RUC"))
        item = self.tabla_proveedores.horizontalHeaderItem(1)
        item.setText(_translate("Proveedores", "Nombre"))
        item = self.tabla_proveedores.horizontalHeaderItem(2)
        item.setText(_translate("Proveedores", "Email"))
        item = self.tabla_proveedores.horizontalHeaderItem(3)
        item.setText(_translate("Proveedores", "Telefono"))
        item = self.tabla_proveedores.horizontalHeaderItem(4)
        item.setText(_translate("Proveedores", "Direccion"))
        self.btn_buscar.setText(_translate("Proveedores", "Buscar"))
        self.cbx_buscar.setItemText(0, _translate("Proveedores", "RUC"))
        self.cbx_buscar.setItemText(1, _translate("Proveedores", "Nombre"))
        self.cbx_buscar.setItemText(2, _translate("Proveedores", "Telefono"))
        self.cbx_buscar.setItemText(3, _translate("Proveedores", "Direccion"))
        self.groupBox.setTitle(_translate("Proveedores", "Datos del proveedor"))
        self.label.setText(_translate("Proveedores", "RUC:"))
        self.label_5.setText(_translate("Proveedores", "Direccion:"))
        self.label_4.setText(_translate("Proveedores", "Telefono:"))
        self.label_2.setText(_translate("Proveedores", "Nombre:"))
        self.label_3.setText(_translate("Proveedores", "Email:"))
        self.btn_crear.setText(_translate("Proveedores", "Crear"))
        self.btn_modificar.setText(_translate("Proveedores", "Modificar"))
        self.btn_eliminar.setText(_translate("Proveedores", "Eliminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = QtWidgets.QWidget()
    proveedores = Proveedores()
    proveedores.setupUi(ui)
    ui.show()
    sys.exit(app.exec_())
